### ISSUE TITLE
Fix Address#country_subdevision_code spelling

### ISSUE THREAD

**Issue by knorrli** [fadendaten/six_saferpay#23]
As noted by @Drinion [here](https://github.com/fadendaten/solidus_six_saferpay/pull/16#discussion_r699929350), the `country_subdivision_code` attribute of the `Address` model contains a spelling mistake that should be fixed. Since the spelling is consistent throughout the project this is also passed to the SIX api and therefore it's currently impossible to submit an actual value for the country subdivision code via this gem.

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by knorrli** [comment]
@mohitsaxenaknoldus thanks for jumping in!

**Comment by mohitsaxenaknoldus** [comment]
Raised PR: https://github.com/fadendaten/six_saferpay/pull/24
